/**
 * Tabela de sobreposição manual e curada de nomes de exercícios em Português do Brasil.
 * Permite definir traduções precisas e naturais para IDs específicos da ExerciseDB
 * ou para nomes exatos em inglês.
 */

// Mapeamento por ID específico (maior precisão)
export const EXERCISE_ID_OVERRIDES: Record<string, string> = {
  // Principais exercícios e compostos
  '0025': 'Supino reto com barra',
  '0043': 'Agachamento livre com barra',
  '0032': 'Levantamento terra com barra',
  '0031': 'Desenvolvimento militar com barra',
  '0027': 'Remada curvada com barra',
  '0007': 'Puxada frontal na polia',
  '0012': 'Rosca bíceps na polia baixa',
  '0019': 'Tríceps corda na polia alta',
  '0028': 'Rosca direta com barra',
  '0023': 'Tríceps testa com barra',
  '0047': 'Elevação lateral com halteres',
  '0041': 'Agachamento búlgaro com halteres',
  '0054': 'Leg press 45°',
  '0038': 'Cadeira extensora',
  '0037': 'Mesa flexora',
  '0042': 'Elevação de panturrilha em pé',
  '0035': 'Elevação pélvica com barra',
  '0009': 'Abdominal supra no solo',
  '0049': 'Prancha isométrica',
  '0046': 'Elevação frontal com halteres',
  '0029': 'Desenvolvimento com halteres sentado',
  '0030': 'Supino inclinado com halteres',
  '0034': 'Crucifixo reto com halteres',
  '0036': 'Stiff com barra',
  '0039': 'Cadeira abdutora',
  '0040': 'Cadeira adutora',
  '0015': 'Remada baixa na polia (pegada triângulo)',
  '0018': 'Tríceps pulley com barra reta',
  '0006': 'Crucifixo na máquina (Peck Deck)',
  '0044': 'Encolhimento de ombros com halteres',
  '0048': 'Crucifixo invertido com halteres',
  '0050': 'Prancha lateral',
  '0014': 'Abdominal no cabo (pulley)',
  '0045': 'Rosca martelo com halteres',
  '0051': 'Barra fixa pronada',
  '0052': 'Paralelas para peitoral e tríceps',
  '0053': 'Flexão de braços no solo',
  '01qpYSe': 'Postura do cachorro olhando para cima',
  '03lzqwk': 'Elevação de joelhos na barra fixa',
  '05Cf2v8': 'Paralelas com pegada fechada'
};

// Mapeamento de nomes exatos em inglês para nomes comuns no Brasil
export const EXACT_NAME_OVERRIDES: Record<string, string> = {
  'barbell bench press': 'Supino reto com barra',
  'barbell incline bench press': 'Supino inclinado com barra',
  'barbell decline bench press': 'Supino declinado com barra',
  'dumbbell bench press': 'Supino reto com halteres',
  'dumbbell incline bench press': 'Supino inclinado com halteres',
  'dumbbell decline bench press': 'Supino declinado com halteres',
  'barbell squat': 'Agachamento livre com barra',
  'barbell back squat': 'Agachamento livre costas',
  'barbell front squat': 'Agachamento frontal com barra',
  'dumbbell squat': 'Agachamento com halteres',
  'goblet squat': 'Agachamento taça (Goblet)',
  'barbell deadlift': 'Levantamento terra com barra',
  'romanian deadlift': 'Levantamento terra romeno (RDL)',
  'stiff-legged deadlift': 'Stiff com barra',
  'sumo deadlift': 'Levantamento terra sumô',
  'barbell overhead press': 'Desenvolvimento de ombros com barra',
  'seated dumbbell shoulder press': 'Desenvolvimento com halteres sentado',
  'dumbbell lateral raise': 'Elevação lateral com halteres',
  'cable lateral raise': 'Elevação lateral na polia',
  'dumbbell front raise': 'Elevação frontal com halteres',
  'bent-over barbell row': 'Remada curvada com barra',
  'one-arm dumbbell row': 'Remada serrote unilateral com halteres',
  'lat pulldown': 'Puxada frontal no pulley',
  'wide-grip lat pulldown': 'Puxada aberta no pulley',
  'cable seated row': 'Remada baixa na polia',
  'barbell bicep curl': 'Rosca direta com barra',
  'dumbbell bicep curl': 'Rosca com halteres alternada',
  'dumbbell hammer curl': 'Rosca martelo com halteres',
  'cable triceps pushdown': 'Tríceps na polia alta',
  'triceps rope pushdown': 'Tríceps corda na polia',
  'lying triceps extension': 'Tríceps testa com barra',
  'barbell hip thrust': 'Elevação pélvica com barra',
  'glute bridge': 'Ponte para glúteos no solo',
  'leg press': 'Leg press 45°',
  'leg extensions': 'Cadeira extensora',
  'leg extension': 'Cadeira extensora',
  'lying leg curls': 'Mesa flexora',
  'lying leg curl': 'Mesa flexora',
  'seated leg curl': 'Cadeira flexora',
  'standing calf raise': 'Elevação de panturrilha em pé',
  'seated calf raise': 'Elevação de panturrilha sentado',
  'pull-up': 'Barra fixa pronada',
  'chin-up': 'Barra fixa supinada',
  'chest dip': 'Paralelas para peitoral',
  'push-up': 'Flexão de braços',
  'incline push-up': 'Flexão inclinada',
  'diamond push-up': 'Flexão diamante',
  'face pull': 'Face pull na polia com corda',
  'cable crunch': 'Abdominal na polia alta',
  'hanging leg raise': 'Elevação de pernas na barra fixa',
  'ab roller': 'Rolo abdominal (Ab Wheel)',
  'plank': 'Prancha isométrica',
  'side plank': 'Prancha lateral',
  'russian twist': 'Giro russo (Russian Twist)'
};
